# Generated by Django 4.1.2 on 2023-09-12 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_birth_date_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date_2',
        ),
    ]
