# Generated by Django 4.1.2 on 2023-09-12 18:57

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_birth_date_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.AddField(
            model_name='user',
            name='company_image',
            field=models.TextField(blank=True, max_length=500, verbose_name='CompanyImage'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='CompanyName'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_companystaff',
            field=models.BooleanField(default=False, verbose_name='CompanyStaff'),
        ),
        migrations.AddField(
            model_name='user',
            name='offers',
            field=models.JSONField(blank=True, default=api.models.company_offer_default, verbose_name='Offers'),
        ),
    ]
