# Generated by Django 4.1.2 on 2023-09-12 19:20

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_bio_remove_user_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_short_name',
            field=models.CharField(blank=True, help_text='Short name of company (to act as simple ID)', max_length=50, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_image',
            field=models.TextField(blank=True, help_text="URL of company's image", max_length=500, verbose_name='Company image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, help_text='Full name of company', max_length=50, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_companystaff',
            field=models.BooleanField(default=False, help_text='Is this user a staff from company?', verbose_name='Is company staff'),
        ),
        migrations.AlterField(
            model_name='user',
            name='offers',
            field=models.JSONField(blank=True, default=api.models.company_offer_default, help_text='Current company offers in JSON format', verbose_name='Company offers'),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, help_text='Price of this offer', verbose_name='Offer price')),
                ('company', models.ForeignKey(help_text='Company that provides this offer', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
