# Generated by Django 4.1.2 on 2023-09-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_company_short_name_alter_user_company_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='company_name',
            field=models.CharField(blank=True, help_text='Full name of company', max_length=50, verbose_name='Company name'),
        ),
    ]
